from PracticeQuestions import PracticeQuestions
from typing import Optional, List, Dict
import os
import tempfile
import re
from celery import shared_task
from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama import ChatOllama
from pydantic import BaseModel, Field
from app.Model.TrainingContent import (
    Question, TrainingContent, Module, Article, Paragraph, 
    Slide, VoiceCover, EvaluationStatus, TotalEvaluation
)
import time
from langchain_core.output_parsers import StrOutputParser
from app.Model.Training import Training
from app.Model.enum.trainingStatus import trainingStatus
from app.mocks.ml_mock import mock_score_predictor
from app.Model.enum.proficiencyLevelInitialQuestions import proficiencyLevelInitialQuestions
from app.routes.dispatcher import push_to_org
from app.routes.dispatcherEm import push_to_em
from gtts import gTTS
import cloudinary
import cloudinary.uploader
from mdtopptx import parse_markdown, create_ppt

# --- SCHEMAS ---
class Component(BaseModel):
    name: str = Field(description="The component extracted as a single word.")
    is_output: bool = Field(description="True if this component is generated as an output, False otherwise.")
    has_connections: bool = Field(description="True if this component connects to any other component.")

class Connection(BaseModel):
    source_component: str = Field(description="The single-word name of the origin component.")
    target_component: str = Field(description="The single-word name of the destination component.")
    relationship: str = Field(description="The text-form description of how they interconnect.")

class ParagraphAnalysis(BaseModel):
    components: List[Component] = Field(
        description="List of all identified components in this specific paragraph."
    )
    connections: List[Connection] = Field(
        description="List of all interconnections between components in this paragraph."
    )
    needs_diagram: bool = Field(
        default=False, # <--- ADD THIS DEFAULT
        description="True ONLY if there is at least one connection between components in this paragraph."
    )
    mermaid_code: Optional[str] = Field(
        default=None,  # <--- ADD THIS DEFAULT
        description="Valid Mermaid.js graph code (e.g., graph TD). Generate ONLY if needs_diagram is True."
    )
class QuizQuestionSchema(BaseModel):
    question: str = Field(description="The text of the evaluation question.")
    answerChoices: list[str] = Field(description="An array of 4 possible answer strings.")
    correctAnswer: int = Field(description="The integer index (0-based) of the correct answer within the answerChoices array.")
    
class EvaluationTestSchema(BaseModel):
    test_questions: list[QuizQuestionSchema] = Field(description="A list of multiple-choice questions for the end-of-module evaluation.")   

class ModuleOutlineSchema(BaseModel):
    name: str = Field(description="The title of the training module.")
    description: str = Field(description="A brief description of the module's content.")

class CourseOutlineSchema(BaseModel):
    title: str = Field(description="The official, professional title of the course.")
    overview: str = Field(description="A clear summary of the course objectives.")
    modules: list[ModuleOutlineSchema] = Field(max_length=2, description="An array of up to 2 modules covering the required skills.")

class singleArticle(BaseModel):
    articleTitle: str = Field(description="Title of the article")
    paragraphs: list[str] = Field(max_length=2, description="List of paragraphs related to the article title")

class allArticles(BaseModel):
    articles: list[singleArticle] = Field(max_length=2, description="All articles generated by AI")
class testQuestionPair(BaseModel):
    question: str
    answer: str
class AllTestQuestions(BaseModel):
    testQSet: List[testQuestionPair] = Field(description="")
class ModuleQuestionSchema(BaseModel):
    question: str = Field(description="The text of the evaluation question.")
    answerChoices: list[str] = Field(min_length=4, max_length=4, description="An array of exactly 4 possible answer strings.")
    correctAnswer: int = Field(description="The integer index (0-based) of the correct answer within the answerChoices array.")

class ModuleEvaluationSchema(BaseModel):
    evaluationQuestions: list[ModuleQuestionSchema] = Field(min_length=10, max_length=10, description="A list of exactly 10 multiple-choice questions for the module.")


# --- HELPER FUNCTIONS ---
def invoke_with_fallback(chain_builder, prompt_args, max_tokens, model_name, initial_llm, step_name="AI Task"):
    """Invoke a LangChain chain with exponential-backoff retries."""
    max_retries = 5
    base_wait = 3.0

    last_exc = None
    for attempt in range(max_retries):
        try:
            chain = chain_builder(initial_llm)
            return chain.invoke(prompt_args)
        except Exception as e:
            last_exc = e
            wait_time = base_wait * (2 ** attempt)
            print(f"[{step_name}] Attempt {attempt + 1}/{max_retries} failed: {repr(e)}. Retrying in {wait_time:.0f}s...", flush=True)
            time.sleep(wait_time)

    raise Exception(f"[{step_name}] All {max_retries} retry attempts failed.") from last_exc


# --- TASKS ---
@shared_task(bind=True)
def generate_initial_questions(self, target_skills: list[str], role: str, employeeID: str, organizationID: str,practiceMidTestsCount:int):
    try:
        ollama_url = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434')
        model_name = os.getenv('OLLAMA_MODEL', 'gpt-oss:120b')
        max_tokens = int(os.getenv('MAX_TOKENS', '4096'))
        api_key = os.getenv('OLLAMA_API_KEY', '')
        
        llm = ChatOllama(
            model=model_name,
            base_url=ollama_url,
            temperature=0.2,
            num_predict=max_tokens,
            **(({"headers": {"Authorization": f"Bearer {api_key}"}}) if api_key else {})
        )
        
        create_initial_questions_prompt = ChatPromptTemplate.from_template(
            "Create 5 diagnostic multiple-choice questions for these skills: {target_skills}. The target employee role is: {role}.\n\n"
            "CRITICAL: You MUST output raw JSON using exactly this structure and these exact key names:\n"
            "{{\n"
            "  \"test_questions\": [\n"
            "    {{\n"
            "      \"question\": \"string\",\n"
            "      \"answerChoices\": [\"string\", \"string\", \"string\", \"string\"],\n"
            "      \"correctAnswer\": 0\n"
            "    }}\n"
            "  ]\n"
            "}}"
        )
        
        generated_test = invoke_with_fallback(
            lambda _llm: create_initial_questions_prompt | _llm.with_structured_output(EvaluationTestSchema),
            {
                "target_skills": ", ".join(target_skills), 
                "role": role
            },
            max_tokens, model_name, llm, step_name="Initial Questions"
        )
        
        all_questions = generated_test.test_questions
        allInitialQuestions = []
        for item in all_questions:
            newQuestion = Question(
                questions=item.question,
                answerChoices=item.answerChoices,
                correctAnswer=item.correctAnswer
            )
            allInitialQuestions.append(newQuestion)
            
        newTraining = TrainingContent(initialQuestions=allInitialQuestions)    
        saved_training = newTraining.save()
        
        previousTrain = Training.objects(employeeID=employeeID)
        predictedScore = mock_score_predictor() if previousTrain else 0.5    
        
        newParentTraining = Training(
            employeeID=employeeID,
            growth=0.0,
            performanceIncrease=0.0,
            trainingStatus=trainingStatus.PENDING,
            trainingContentID=str(saved_training.id),
            trainingPassStatus=False,
            extractedNewSkillsInModeule=[],
            predictedFinalScore=predictedScore,
            organizationID=organizationID,
            practiceMidTestsCount=practiceMidTestsCount
        )
        newParentTraining.save()
        
        message = {
            "status": "success",
            "type": "AI",
            "message": "Initial questions are created",
            "additionalData": generated_test.model_dump()
        }
        print(f"DEBUG: [TASK] Task generate_initial_questions finished for Org {organizationID}.", flush=True)
        push_to_org(organizationID, message)
        return generated_test.model_dump()

    except Exception as exc:
        self.retry(exc=exc, countdown=5, max_retries=0)


@shared_task(bind=True)
def create_course(self, contentID: str, role: str, target_skills: list[str], proficiencyLevel: proficiencyLevelInitialQuestions, employeeID: str):
    try:
        if isinstance(proficiencyLevel, str):
            proficiencyLevel = proficiencyLevelInitialQuestions(proficiencyLevel)
            
        ollama_url = os.getenv('OLLAMA_BASE_URL', 'https://ollama.com')
        model_name = os.getenv('OLLAMA_MODEL', 'gpt-oss:120b')
        max_tokens = int(os.getenv('MAX_TOKENS', '4096'))
        api_key = os.getenv('OLLAMA_API_KEY', '')
        
        llm = ChatOllama(
            model=model_name,
            base_url=ollama_url,
            temperature=0.2,
            num_predict=max_tokens,
            **(({"headers": {"Authorization": f"Bearer {api_key}"}}) if api_key else {})
        )

        create_base_course_outline = ChatPromptTemplate.from_template(
            "You are an expert corporate instructional designer. "
            "Design a training course for a {role} focusing on these target skills: {target_skills}. "
            "CRITICAL: The content complexity must be strictly tailored for a learner with a {proficiency_level} proficiency level. "
            "Provide a course title, a brief overview, and an outline of exactly 2 modules.\n\n"
            "CRITICAL: You MUST output raw JSON using exactly this structure and these exact key names:\n"
            "{{\n"
            "  \"title\": \"string\",\n"
            "  \"overview\": \"string\",\n"
            "  \"modules\": [\n"
            "    {{\n"
            "      \"name\": \"string\",\n"
            "      \"description\": \"string\"\n"
            "    }}\n"
            "  ]\n"
            "}}"
        )

        generated_course = invoke_with_fallback(
            lambda _llm: create_base_course_outline | _llm.with_structured_output(CourseOutlineSchema),
            {
                "target_skills": ", ".join(target_skills),
                "role": role,
                "proficiency_level": proficiencyLevel.value
            },
            max_tokens, model_name, llm, step_name="Course Outline"
        )

        create_article_prompt = ChatPromptTemplate.from_template(
            "You are an expert technical writer. Create detailed educational articles for a training module.\n"
            "Module Name: {module_name}\n"
            "Module Description: {module_description}\n"
            "Target Audience Proficiency: {proficiency_level}\n\n"
            "CRITICAL INSTRUCTIONS:\n"
            "1. Write up to 2 articles covering this module.\n"
            "2. Each article must have up to 2 distinct paragraphs.\n"
            "3. Keep the content strictly aligned with the module description and tailored to the proficiency level.\n\n"
            "CRITICAL: You MUST output raw JSON using exactly this structure and these exact key names:\n"
            "{{\n"
            "  \"articles\": [\n"
            "    {{\n"
            "      \"articleTitle\": \"string\",\n"
            "      \"paragraphs\": [\"string\", \"string\"]\n"
            "    }}\n"
            "  ]\n"
            "}}"
        )

        create_slides_md_prompt = ChatPromptTemplate.from_template(
            "You are an expert presentation designer. Create a slide deck presentation for a training module.\n"
            "Module Name: {module_name}\n"
            "Module Description: {module_description}\n"
            "Target Audience Proficiency: {proficiency_level}\n\n"
            "CRITICAL INSTRUCTIONS FOR MDTOPPTX FORMAT:\n"
            "1. Output ONLY valid Markdown text.\n"
            "2. Use exactly three hyphens (---) on a new line to separate every slide.\n"
            "3. Slide 1 must be a Title Slide using a single '#' for the main title.\n"
            "4. Create 3 to 4 content slides. Use '##' for content slide titles.\n"
            "5. Use standard bullet points ('-') for the body text. Keep bullets concise (max 15 words)."
        )
        create_practice_tests_prompt = ChatPromptTemplate.from_template("")
        trainingObj = Training.objects(trainingContentID=contentID)
        if trainingObj:
            testQuestionsRes = invoke_with_fallback(
                lambda _llm: create_practice_tests_prompt | _llm.with_structured_output(AllTestQuestions),
                {
                    "practiceMidTestsCount": trainingObj.practiceMidTestsCount
                },
                max_tokens, model_name, llm, step_name="Practice question generation"
            )
            extractePQ = testQuestionsRes.testQSet
            newPracticeQuestion = PracticeQuestions(
                allQuestions = extractePQ,
                trainingID = trainingObj.id
            )
            newPracticeQuestion.save()
        create_module_eval_prompt = ChatPromptTemplate.from_template(
            "You are an expert technical assessor. Create an end-of-module evaluation quiz.\n"
            "Module Name: {module_name}\n"
            "Module Description: {module_description}\n"
            "Target Audience Proficiency: {proficiency_level}\n\n"
            "CRITICAL INSTRUCTIONS:\n"
            "1. Generate exactly 10 multiple-choice questions.\n"
            "2. The questions must strictly test the concepts covered in the module description.\n"
            "3. The technical depth and vocabulary must perfectly match the {proficiency_level} proficiency level.\n"
            "4. Ensure there is only one unambiguous correct answer per question.\n\n"
            "CRITICAL: You MUST output raw JSON using exactly this structure and these exact key names:\n"
            "{{\n"
            "  \"evaluationQuestions\": [\n"
            "    {{\n"
            "      \"question\": \"string\",\n"
            "      \"answerChoices\": [\"string\", \"string\", \"string\", \"string\"],\n"
            "      \"correctAnswer\": 0\n"
            "    }}\n"
            "  ]\n"
            "}}"
        )
        
        all_db_modules = []
        for module in generated_course.modules:
            time.sleep(2) 
            
            # 1. Native Structured Output for Articles
            generated_articles_data = invoke_with_fallback(
                lambda _llm: create_article_prompt | _llm.with_structured_output(allArticles),
                {
                    "module_name": module.name,
                    "module_description": module.description,
                    "proficiency_level": proficiencyLevel.value
                },
                max_tokens, model_name, llm, step_name="Article Generation"
            )

            system_instructions = \
"""You are a technical extraction system. Analyze the provided paragraph from the article.
Follow this exact algorithm for THIS PARAGRAPH ONLY:
1. Identify components (outputs or non-outputs) mentioned in the text. Extract them as single words.
2. Determine if these components have interconnections or common characteristics within this specific paragraph.
3. Classify each component's output status (True/False).
4. Match each component against others to map interconnections in text form (source, target, relationship).
5. If ANY interconnections exist, set needs_diagram to True and generate valid Mermaid.js flowchart code using the extracted connections.

CRITICAL: You MUST output raw JSON using exactly this structure and these exact key names. Do NOT use markdown code fences.
{{
  "components": [{{"name": "string", "is_output": true, "has_connections": true}}],
  "connections": [{{"source_component": "string", "target_component": "string", "relationship": "string"}}],
  "needs_diagram": true,
  "mermaid_code": "string or null"
}}"""

            paragraph_eval_prompt = ChatPromptTemplate.from_messages([
                ("system", system_instructions),
                ("human", "Article Title: {articleTitle}\n\nParagraph Content:\n{paragraph}")
            ])

            db_articles = []
            for art in generated_articles_data.articles:
                db_paragraphs = []
                for p_text in art.paragraphs:
                    time.sleep(1.5)
                    try:
                        # 2. Native Structured Output for Paragraph Eval
                        evalData = invoke_with_fallback(
                            lambda _llm: paragraph_eval_prompt | _llm.with_structured_output(ParagraphAnalysis),
                            {
                                "articleTitle": art.articleTitle,
                                "paragraph": p_text
                            },
                            max_tokens, model_name, llm, step_name="Paragraph Analysis"
                        )
                    except Exception as parse_err:
                        print(f"[Paragraph Analysis] Failed: {repr(parse_err)}", flush=True)
                        evalData = ParagraphAnalysis(
                            components=[], connections=[],
                            needs_diagram=False, mermaid_code=None
                        )
                    
                    db_paragraphs.append(Paragraph(
                        paragraph=p_text,
                        components=[comp.model_dump() for comp in evalData.components],
                        connections=[conn.model_dump() for conn in evalData.connections],
                        has_diagram=evalData.needs_diagram,
                        mermaid_diagram=evalData.mermaid_code if evalData.needs_diagram else None
                    ))
                    
                db_articles.append(Article(
                    articleTitle=art.articleTitle, 
                    paragraphs=db_paragraphs
                ))

            # 3. Standard Text Output for Slides (Needs Markdown, not JSON)
            time.sleep(2) 
            generated_markdown_string = invoke_with_fallback(
                lambda _llm: create_slides_md_prompt | _llm | StrOutputParser(),
                {
                    "module_name": module.name,
                    "module_description": module.description,
                    "proficiency_level": proficiencyLevel.value
                },
                max_tokens, model_name, llm, step_name="Slides Generation"
            )

            # 4. Native Structured Output for Evaluation Questions
            time.sleep(2) 
            eval_data = invoke_with_fallback(
                lambda _llm: create_module_eval_prompt | _llm.with_structured_output(ModuleEvaluationSchema),
                {
                    "module_name": module.name,
                    "module_description": module.description,
                    "proficiency_level": proficiencyLevel.value
                },
                max_tokens, model_name, llm, step_name="Module Evaluation"
            )
            
            db_evaluation_questions = []
            for q in eval_data.evaluationQuestions:
                new_db_question = Question(
                    questions=q.question,          
                    answerChoices=q.answerChoices, 
                    correctAnswer=q.correctAnswer  
                )
                db_evaluation_questions.append(new_db_question)
            
            # --- Presentation & Media Generation ---
            safe_module_name = re.sub(r'[^a-zA-Z0-9_]', '_', module.name)
            output_filename = os.path.join(tempfile.gettempdir(), f"module_{safe_module_name}_{contentID}_slides.pptx")
            
            parsed_slides = parse_markdown(generated_markdown_string)
            total_slide_count = len(parsed_slides)
            create_ppt(parsed_slides, output_filename)
            
            upload_result = cloudinary.uploader.upload(
                output_filename, 
                resource_type="raw",
                folder=f"skillio/courses/{contentID}/slides", 
                public_id=f"module_{safe_module_name}_slides"
            )
            cloud_slide_url = upload_result.get("secure_url")

            local_audio_files = []
            voice_covers_data = []
            
            for index, slide in enumerate(parsed_slides):
                slide_number = index + 1
                if isinstance(slide, dict):
                    title_text = slide.get('title', '')
                    raw_content = slide.get('content', [])
                    clean_text = [str(item[-1]) if isinstance(item, tuple) else str(item) for item in raw_content]
                    body_text = ". ".join(clean_text)
                elif isinstance(slide, (list, tuple)) and len(slide) >= 2:
                    title_text = str(slide[0])
                    if isinstance(slide[1], list):
                        clean_text = [str(item[-1]) if isinstance(item, tuple) else str(item) for item in slide[1]]
                        body_text = ". ".join(clean_text)
                    else:
                        body_text = str(slide[1])
                else:
                    continue

                script_text = f"{title_text}. {body_text}"
                if not script_text.strip():
                    continue
                    
                tts = gTTS(text=script_text, lang='en', slow=False) 
                audio_filename = os.path.join(tempfile.gettempdir(), f"slide_{slide_number}_{contentID}.mp3")
                tts.save(audio_filename) 
                local_audio_files.append(audio_filename)
                audio_upload = cloudinary.uploader.upload(
                    audio_filename, 
                    resource_type="video", 
                    folder=f"skillio/courses/{contentID}/audio"
                )
                voice_covers_data.append({
                    "slideNumber": str(slide_number),
                    "voiceFileLink": audio_upload.get("secure_url")
                })
            
            db_voice_covers = [
                VoiceCover(slideNumber=vc['slideNumber'], voiceFileLink=vc['voiceFileLink']) 
                for vc in voice_covers_data
            ]
            
            db_slide = Slide(
                slideName=f"{module.name} Presentation",
                slideLink=cloud_slide_url,
                totSlideCount=total_slide_count,
                voiceCovers=db_voice_covers
            )

            db_eval_status = EvaluationStatus(
                passedStatus=None,
                passLimit=None,
                obtainedMarks=None,
                totalCorrectedCount=None,
                obtainedMarksPrecent=None,
                totalQuestions=len(db_evaluation_questions)
            )

            db_module = Module(
                moduleTitle=module.name,
                moduleDescription=module.description,
                articles=db_articles,
                slides=[db_slide],
                evaluationQuestions=db_evaluation_questions,
                evaluationStatus=db_eval_status
            )
            all_db_modules.append(db_module)

            if os.path.exists(output_filename):
                os.remove(output_filename)
            for audio_file in local_audio_files:
                if os.path.exists(audio_file):
                    os.remove(audio_file)    
        
        training_doc = TrainingContent.objects(id=contentID).first()
        if training_doc:
            training_doc.update(
                set__title=generated_course.title,
                set__overview=generated_course.overview,
                set__modules=all_db_modules,
                set__totalEvaluation=TotalEvaluation(
                    passModuleLimitCount=None,
                    actualPassedModuleCount=None,
                    totalMarks=None,
                    totalMrksPercent=None
                )
            )

        message = {
            "status": "success",
            "type": "AI",
            "message": "Complete course is created"
        }
        push_to_em(employeeID, message)
        return {"status": "success", "contentID": contentID}

    except Exception as exc:
        self.retry(exc=exc, countdown=5, max_retries=0)