import os
import tempfile
import re
from celery import shared_task
from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq 
from pydantic import BaseModel, Field
from app.Model.TrainingContent import (
    Question, TrainingContent, Module, Article, Paragraph, 
    Slide, VoiceCover, EvaluationStatus, TotalEvaluation
)
from app.Model.enum.proficiencyLevelInitialQuestions import proficiencyLevelInitialQuestions
from gtts import gTTS
from langchain_core.output_parsers import StrOutputParser

import cloudinary
import cloudinary.uploader
from mdtopptx import parse_markdown, create_ppt

class QuizQuestionSchema(BaseModel):
    # Minor tweak: changed 'questions' to 'question' for better JSON semantics, but either works.
    question: str = Field(
        description="The text of the evaluation question."
    )
    answerChoices: list[str] = Field(
        description="An array of 4 possible answer strings."
    )
    correctAnswer: int = Field(
        description="The integer index (0-based) of the correct answer within the answerChoices array."
    )
    
class EvaluationTestSchema(BaseModel):
    test_questions: list[QuizQuestionSchema] = Field(
        description="A list of multiple-choice questions for the end-of-module evaluation."
    )   
#for the course outline
class ModuleOutlineSchema(BaseModel):
    name: str = Field(description="The title of the training module.")
    description: str = Field(description="A brief description of the module's content.")

class CourseOutlineSchema(BaseModel):
    title: str = Field(description="The official, professional title of the course.")
    overview: str = Field(description="A clear summary of the course objectives.")
    modules: list[ModuleOutlineSchema] = Field(
        max_length=2, 
        description="An array of up to 2 modules covering the required skills."
    )

     

#to create articles
class singleParagraph(BaseModel):
    paragraph: str = Field(description="Paragraph of the article")
class singleArticle(BaseModel):
    articleTitle: str = Field(description="Title of the article")
    paragraphs: list[singleParagraph] = Field(max_length=2,description="Holds many paragraphs related to the article title")
class allArticles(BaseModel):
    articles: list[singleArticle] = Field(max_length=2,description="All articles generated by AI")



#to create the final end module questions
class ModuleQuestionSchema(BaseModel):
    question: str = Field(description="The text of the evaluation question.")
    answerChoices: list[str] = Field(
        min_length=4, 
        max_length=4, 
        description="An array of exactly 4 possible answer strings."
    )
    correctAnswer: int = Field(
        description="The integer index (0-based) of the correct answer within the answerChoices array."
    )

class ModuleEvaluationSchema(BaseModel):
    evaluationQuestions: list[ModuleQuestionSchema] = Field(
        min_length=10,
        max_length=10,
        description="A list of exactly 10 multiple-choice questions for the module."
    )

@shared_task(bind=True)
def generate_initial_questions(self, target_skills: list[str], role: str):
    try:
        # 1. Use local variables instead of 'self.llm'
        api_key = os.getenv('GROQ_KEY')
        model_name = os.getenv('GROQ_MODEL', "qwen/qwen3-32b")
        llm = ChatGroq(temperature=0.2, model_name=model_name, api_key=api_key)

        
        # 2. Refined prompt for clarity
        create_initial_questions_prompt = ChatPromptTemplate.from_template(
            "Create 5 diagnostic multiple-choice questions for these skills: {target_skills}. The target employee role is: {role}."
        )
        
        initial_questions_chain = create_initial_questions_prompt | llm.with_structured_output(EvaluationTestSchema)
        
        #Create the test
        generated_test = initial_questions_chain.invoke({
            "target_skills": ", ".join(target_skills), 
            "role": role
        })
        #access the created initial data
        all_questions = generated_test.test_questions
        #data saving part
        allInitialQuestions = []
        for index, item in enumerate(all_questions):
            question_text = item.question
            choices = item.answerChoices
            correct_idx = item.correctAnswer

            #access choices one by one
            newQuestion = Question(
                questions=question_text,
                answerChoices=choices,
                correctAnswer=correct_idx
            )
            allInitialQuestions.append(newQuestion)
        newTraining = TrainingContent(
            initialQuestions=allInitialQuestions
        )    
        newTraining.save()

        # 4. Return the parsed JSON dictionary
        return generated_test.model_dump()

    except Exception as exc:
        # If the API times out or fails to return valid JSON, retry in 5 seconds
        self.retry(exc=exc, countdown=5, max_retries=3)

@shared_task(bind=True)
def create_course(self, contentID: str, role: str, target_skills: list[str], proficiencyLevel: proficiencyLevelInitialQuestions):
    try:
        # Convert string to enum if necessary (for Celery serialization)
        if isinstance(proficiencyLevel, str):
            proficiencyLevel = proficiencyLevelInitialQuestions(proficiencyLevel)
            
        api_key = os.getenv('GROQ_KEY')
        model_name = os.getenv('GROQ_MODEL', "qwen/qwen3-32b")
        llm = ChatGroq(temperature=0.2, model_name=model_name, api_key=api_key)

        # create the outline + module outlines
        create_base_course_outline = ChatPromptTemplate.from_template(
            "You are an expert corporate instructional designer. "
            "Design a training course for a {role} focusing on these target skills: {target_skills}. "
            "CRITICAL: The content complexity must be strictly tailored for a learner with a {proficiency_level} proficiency level. "
            "Provide a course title, a brief overview, and an outline of exactly 2 modules."
        )

        course_chain = create_base_course_outline | llm.with_structured_output(CourseOutlineSchema)
        generated_course = course_chain.invoke({
            "target_skills": ", ".join(target_skills),
            "role": role,
            "proficiency_level": proficiencyLevel.value
        })
        # create the articles for each modules
        create_article_prompt = ChatPromptTemplate.from_template(
            "You are an expert technical writer. Create detailed educational articles for a training module.\n"
            "Module Name: {module_name}\n"
            "Module Description: {module_description}\n"
            "Target Audience Proficiency: {proficiency_level}\n"
            "CRITICAL: Write up to 2 articles covering this module. Each article must have up to 2 distinct paragraphs. "
            "Keep the content strictly aligned with the module description and tailored to the proficiency level."
        )
        article_chain = create_article_prompt | llm.with_structured_output(allArticles)
        # create slides md code
        create_slides_md_prompt = ChatPromptTemplate.from_template(
            "You are an expert presentation designer. Create a slide deck presentation for a training module.\n"
            "Module Name: {module_name}\n"
            "Module Description: {module_description}\n"
            "Target Audience Proficiency: {proficiency_level}\n\n"
            "CRITICAL INSTRUCTIONS FOR MDTOPPTX FORMAT:\n"
            "1. Output ONLY valid Markdown text.\n"
            "2. Use exactly three hyphens (---) on a new line to separate every slide.\n"
            "3. Slide 1 must be a Title Slide using a single '#' for the main title.\n"
            "4. Create 3 to 4 content slides. Use '##' for content slide titles.\n"
            "5. Use standard bullet points ('-') for the body text. Keep bullets concise (max 15 words)."
        )
        # need to extract the raw test from the AI response
        string_parser = StrOutputParser()
        slides_md_chain = create_slides_md_prompt | llm | string_parser
        # create evaluation questions
        create_module_eval_prompt = ChatPromptTemplate.from_template(
            "You are an expert technical assessor. Create an end-of-module evaluation quiz.\n"
            "Module Name: {module_name}\n"
            "Module Description: {module_description}\n"
            "Target Audience Proficiency: {proficiency_level}\n\n"
            "CRITICAL INSTRUCTIONS:\n"
            "1. Generate exactly 10 multiple-choice questions.\n"
            "2. The questions must strictly test the concepts covered in the module description.\n"
            "3. The technical depth and vocabulary must perfectly match the {proficiency_level} proficiency level.\n"
            "4. Ensure there is only one unambiguous correct answer per question."
        )
        module_eval_chain = create_module_eval_prompt | llm.with_structured_output(ModuleEvaluationSchema)
        
        # data assemble part in each module
        all_db_modules = []
        for module in generated_course.modules:
            # Invoke the article chain for the current module
            generated_articles_data = article_chain.invoke({
                "module_name": module.name,
                "module_description": module.description,
                "proficiency_level": proficiencyLevel.value
            })

            # Prepare Articles for DB
            db_articles = []
            for art in generated_articles_data.articles:
                db_paragraphs = [Paragraph(paragraph=p.paragraph) for p in art.paragraphs]
                db_articles.append(Article(articleTitle=art.articleTitle, paragraphs=db_paragraphs))

            # invoke the slides creator chain
            generated_markdown_string = slides_md_chain.invoke({
                "module_name": module.name,
                "module_description": module.description,
                "proficiency_level": proficiencyLevel.value
            })
            # invoke the evaluation questions
            eval_data = module_eval_chain.invoke({
                "module_name": module.name,
                "module_description": module.description,
                "proficiency_level": proficiencyLevel.value
            })
            db_evaluation_questions = []
            for q in eval_data.evaluationQuestions:
                new_db_question = Question(
                    questions=q.question,          
                    answerChoices=q.answerChoices, 
                    correctAnswer=q.correctAnswer  
                )
                db_evaluation_questions.append(new_db_question)
            
            # prepare the slides file and upload to cloudinary
            safe_module_name = re.sub(r'[^a-zA-Z0-9_]', '_', module.name)
            output_filename = os.path.join(tempfile.gettempdir(), f"module_{safe_module_name}_{contentID}_slides.pptx")
            
            parsed_slides = parse_markdown(generated_markdown_string)
            total_slide_count = len(parsed_slides)  # get the slide count
            create_ppt(parsed_slides, output_filename)
            
            upload_result = cloudinary.uploader.upload(
                output_filename, 
                resource_type="raw",
                folder=f"skillio/courses/{contentID}/slides", 
                public_id=f"module_{safe_module_name}_slides"
            )
            cloud_slide_url = upload_result.get("secure_url")

            
            local_audio_files = []
            voice_covers_data = []
            # create voices for each slide and save them
            for index, slide in enumerate(parsed_slides):
                slide_number = index + 1
                
                # Handle cases where slide might be a tuple or a dict
                if isinstance(slide, dict):
                    title_text = slide.get('title', '')
                    
                    # Safely unpack tuples if the dict format also contains them
                    raw_content = slide.get('content', [])
                    clean_text = [str(item[-1]) if isinstance(item, tuple) else str(item) for item in raw_content]
                    body_text = ". ".join(clean_text)

                elif isinstance(slide, (list, tuple)) and len(slide) >= 2:
                    title_text = str(slide[0])
                    
                    if isinstance(slide[1], list):
                        # Unpack the tuple to grab the actual text (which is the last item)
                        clean_text = [str(item[-1]) if isinstance(item, tuple) else str(item) for item in slide[1]]
                        body_text = ". ".join(clean_text)
                    else:
                        # Fallback if slide[1] is just a single string or unexpected format
                        body_text = str(slide[1])
                        
                else:
                    continue

                script_text = f"{title_text}. {body_text}"

                # If the slide is empty, skip audio generation
                if not script_text.strip():
                    continue
                tts = gTTS(text=script_text, lang='en', slow=False)  # create the audio
                audio_filename = os.path.join(tempfile.gettempdir(), f"slide_{slide_number}_{contentID}.mp3")
                tts.save(audio_filename)  # save file (mp3)
                local_audio_files.append(audio_filename)
                audio_upload = cloudinary.uploader.upload(
                    audio_filename, 
                    resource_type="video", 
                    folder=f"skillio/courses/{contentID}/audio"
                )
                voice_covers_data.append({
                    "slideNumber": str(slide_number),
                    "voiceFileLink": audio_upload.get("secure_url")
                })
            
            # Prepare VoiceCovers for DB
            db_voice_covers = [
                VoiceCover(slideNumber=vc['slideNumber'], voiceFileLink=vc['voiceFileLink']) 
                for vc in voice_covers_data
            ]
            
            # Prepare Slide object
            db_slide = Slide(
                slideName=f"{module.name} Presentation",
                slideLink=cloud_slide_url,
                totSlideCount=total_slide_count,
                voiceCovers=db_voice_covers
            )

            # Initialize Evaluation Status with None/Defaults
            db_eval_status = EvaluationStatus(
                passedStatus=None,
                passLimit=None,
                obtainedMarks=None,
                totalCorrectedCount=None,
                obtainedMarksPrecent=None,
                totalQuestions=len(db_evaluation_questions)
            )

            # Assemble Module
            db_module = Module(
                moduleTitle=module.name,
                moduleDescription=module.description,
                articles=db_articles,
                slides=[db_slide],
                evaluationQuestions=db_evaluation_questions,
                evaluationStatus=db_eval_status
            )
            all_db_modules.append(db_module)

            # remove the slides file
            if os.path.exists(output_filename):
                os.remove(output_filename)
            # remove audio files
            for audio_file in local_audio_files:
                if os.path.exists(audio_file):
                    os.remove(audio_file)    
        
        # Final data adding - Update the TrainingContent document
        training_doc = TrainingContent.objects(id=contentID).first()
        if training_doc:
            training_doc.update(
                set__title=generated_course.title,
                set__overview=generated_course.overview,
                set__modules=all_db_modules,
                set__totalEvaluation=TotalEvaluation(
                    passModuleLimitCount=None,
                    actualPassedModuleCount=None,
                    totalMarks=None,
                    totalMrksPercent=None
                )
            )
        
        return {"status": "success", "contentID": contentID}

    except Exception as exc:
        # If the API times out or fails to return valid JSON, retry in 5 seconds
        self.retry(exc=exc, countdown=5, max_retries=2)
    
